service: guardduby
frameworkVersion: ">=2.68.0"


provider:
  name: aws
  stage: dev
  runtime: go1.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221


functions:
  slack:
    handler: main
    role: GuardDutyLambda
    timeout: 30
    description: GuardDutyLambda slack notice
    memorySize: 128
    environment:
      SLACK_TOKEN: ${opt:slacktoken}
      CHANNEL_ID: ${opt:channelid}
      THRESHOLD: ${opt:threshold}
    events:
      - eventBridge:
          pattern:
            source:
              - aws.guardduty
            detail-type:
              - GuardDuty Finding


resources:
  Resources:
    GuardDutyLambda:
      Type: AWS::IAM::Role
      Properties:
        RoleName: GuardDutyLambda
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        Policies:
          - PolicyName: GuardDutyLambda
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "*"
